### ISSUE TITLE
Support for definining storageClassNames

### ISSUE THREAD

**Issue by MisterTimn** [streamnative/charts#126]
We've been switching over from a custom pulsar helm deployment to using this one.

I've noticed that the PVC template functions either use a local-storage class or define a new one based on the `storageClass` object within the different components.

In our on-prem k8s cluster we have already defined several storageclasses, so we would only need a place to add our `storageClassName` so an appropriate PVC is made.

e.g.

```yaml
zookeeper:
  component: zookeeper
  replicaCount: 3
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 50Gi
      local_storage: false
      storageClassName: <our-custom-storageclass>
```

Now we can only deploy relying on our `default` storageclass but this is less then ideal.

Is it enough to add this `storageClassName` entry to all component's volumes object and add a clause to the template functions which make the PVCs? I could add this and start a pull request.
