### ISSUE TITLE
Failing Helm upgrade 1.2.2 to 1.3.1

### ISSUE THREAD

**Issue by MisterTimn** [streamnative/charts#143]
Trying to upgrade to latest chart version but apparently there are changes to the statefulset of bookkeeper

'''
Error: UPGRADE FAILED: cannot patch "pulsar-bookie" with kind StatefulSet: StatefulSet.apps "pulsar-bookie" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
'''

These are the only values for bookie that I override/set:
```yaml
bookkeeper:
  component: bookie
  replicaCount: 4
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    journal:
      name: journal
      size: 10Gi
      local_storage: false
      ## If the storage class is left undefined when using persistence
      ## the default storage class for the cluster will be used.
      ##
    ledgers:
      name: ledgers
      size: 5Gi
      local_storage: false
```

Upgrading from Chart version 1.2.2 to 1.3.1

What would be the best approach to perform the upgrade here? Some settings I need to set or will I have to remove the statefulset entirely?

**Comment by sijie** [comment]
@MisterTimn Apologies that we don't follow up on this issue as early as possible! 

In 1.3.1, there is a change in anti-affinity rules. We change the default from `requiredDuringSchedulingIgnoredDuringExecution` to `preferredDuringSchedulingIgnoredDuringExecution`. So in order to upgrade from 1.2.1 to 1.3.1, you can add the following settings to set the affinity type to `requiredDuringSchedulingIgnoredDuringExecution`.

```
zookeeper:
  affinity:
    type: requiredDuringSchedulingIgnoredDuringExecution
bookkeeper:
  affinity:
    type: requiredDuringSchedulingIgnoredDuringExecution
autorecovery:
  affinity:
    type: requiredDuringSchedulingIgnoredDuringExecution
broker:
  affinity:
    type: requiredDuringSchedulingIgnoredDuringExecution
proxy:
  affinity:
    type: requiredDuringSchedulingIgnoredDuringExecution
```

Let me know if you run into any issues.
