### ISSUE TITLE
Apply PulsarTenant, throw exception Clusters do not exist

### ISSUE THREAD

**Issue by tuteng** [streamnative/charts#415]
```
#   tenants:
#   # tenant name
#   - name: cloud
#     # the parameters for creating tenant
#     config:
#       # The list of auth principal allowed to administrate the tenant
#       # +optional
#       adminRoles:
#       - admin
#       # The list of allowed clusters. If empty, the tenant will have access to all clusters
#       # +optional
#       allowedClusters:
#       - pulsar
```
PulsarTenant using the default value `pulsar` throws the following exception:

```
status:
  conditions:
  - lastTransitionTime: "2021-12-13T03:33:02Z"
    message: 'code: 412 reason: Clusters do not exist'
    observedGeneration: 1
    reason: ReconcileError
    status: "False"
    type: Ready
```

It is recommended that this field `allowedClusters` be updated as required, see the behavior of pulsar-admin
