### ISSUE TITLE
Missing imagePullSecret for vault manifests

### ISSUE THREAD

**Issue by ahothan** [streamnative/charts#490]
Deploying sn-platform when using private container registry fails because these 2 manifests are missing imagePullSecret:

https://github.com/streamnative/charts/blob/master/charts/sn-platform/templates/vault/vault-statefulset.yaml
https://github.com/streamnative/charts/blob/master/charts/sn-platform/templates/vault/vault-initialize.yaml

Missing under spec:
```
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
```

**Comment by ahothan** [comment]
Looks like vault-statefulset.yaml defines a CR called Vault, to which adding an imagePullSecret is may not be supported
as it does not have the usual containers field under spec: 
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.vault.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.vault.component }}
spec:
  size: 3
  image: "{{ .Values.images.vault.repository }}:{{ .Values.images.vault.tag }}"
  serviceAccount: {{ template "pulsar.vault.serviceAccount" . }}
  serviceType: {{ .Values.vault.serviceType }}

  statsdDisabled: true
  ```
  
  Instead, perhaps insert the imagePullSecret in the associated service account (vault-service-account.yaml)
  ```
  kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "pulsar.vault.serviceAccount" . }}
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
 ```  
 
 add at the end:
 ```
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
    - name: {{ .Values.imagePullSecrets }}
  {{- end }}
  ```
 as described in https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account
