### ISSUE TITLE
Issue with TLS  and cert-manager

### ISSUE THREAD

**Issue by bsheltonihs** [streamnative/charts#492]
### Issue
When the option below is set to `true` in the values.yaml it fails with "the server could not find the requested resource". The TLS templates have hardcoded api entries for `apiVersion: cert-manager.io/v1alpha2`  that they try to for the call. This is causing issues and make TLS unusable for our use-case. In addition to that according to cert-manager.io this has been deprecated as of version 1.6.0 [cert-manager v1.6.0 change log](https://cert-manager.io/docs/release-notes/release-notes-1.6/#v1-6-0).

````yaml
certs:
    internal_issuer:
      enabled: false
      component: internal-cert-issuer
      type: selfsigning
````
###  Solution
If `apiVersion` was made into a variable that can be changed via the `value.yaml` it would resolve the issue as well as allow for other solutions to provide self signed certs.
