### ISSUE TITLE
[sn-platform] Failed to enable TLS with cert-manager 1.x

### ISSUE THREAD

**Issue by sijie** [streamnative/charts#554]
**Motivation**

When enabling TLS with an internal issuer, the sn-platform failed to install. 

```
certs:
  internal_issuer:
    enabled: true

<<omit other settings>>

tls:
  enabled: true
  # common settings for generating certs
  common:
    # 90d
    duration: 2160h
    # 15d
    renewBefore: 360h
    organization:
      - pulsar
    keySize: 4096
    keyAlgorithm: rsa
    keyEncoding: pkcs8
  # settings for generating certs for proxy
  proxy:
    enabled: true
    cert_name: tls-proxy
    untrustedCa: true
  # settings for generating certs for proxy
  pulsar_detector:
    enabled: false
    cert_name: tls-pulsar-detector
  # settings for generating certs for broker
  broker:
    enabled: true
    cert_name: tls-broker
  functions:
    enabled: false
    cert_name: tls-function
  # settings for generating certs for bookies
  bookie:
    enabled: true
    cert_name: tls-bookie
  # settings for generating certs for zookeeper
  zookeeper:
    enabled: true
    cert_name: tls-zookeeper
  # settings for generating certs for recovery
  autorecovery:
    cert_name: tls-recovery
  # settings for generating certs for toolset
  toolset:
    cert_name: tls-toolset
  presto:
    enabled: false
    cert_name: tls-presto
  streamnative_console:
    enabled: false
    cert_name: tls-streamnative_console
```

It will fail with the following error:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Certificate.spec): unknown field "keyAlgorithm" in io.cert-manager.v1.Certificate.spec, ValidationError(Certificate.spec): unknown field "keyEncoding" in io.cert-manager.v1.Certificate.spec, ValidationError(Certificate.spec): unknown field "keySize" in io.cert-manager.v1.Certificate.spec, ValidationError(Certificate.spec): unknown field "organization" in io.cert-manager.v1.Certificate.spec]
```

The `Certificate` type has changed over time.  `v1` doesn’t contain `keyEncoding` since `v1alpha3`.  Yet the sn-platform chart thinks it does: https://github.com/streamnative/charts/blob/master/charts/sn-platform/templates/tls/tls-certs-internal.yaml#L42-L44

It seems that we comment out the `keyEncoding` from proxy certs (https://github.com/streamnative/charts/blob/master/charts/sn-platform/templates/tls/tls-certs-internal.yaml#L42) and but not from the other certs (https://github.com/streamnative/charts/blob/master/charts/sn-platform/templates/tls/tls-certs-internal.yaml#L88). We might need to make sure the certificate is aligned with the version of cert-manager we are using.

We should also consider making the API version configurable as well. See reference: https://github.com/apache/pulsar-helm-chart/pull/107
