### ISSUE TITLE
Configuring the nodeSelector property for vault does not take effect

### ISSUE THREAD

**Issue by futeng** [streamnative/charts#631]
I added the a `nodeSelector` in `values.yaml`, which does not exist by default. 
And it dose not take effect.

Is this a problem that will be considered for fix?

```yaml
vault:
  component: "vault"
  nodeSelector:
    zone: default
  serviceAccount:
    created: true
    name: ""
  serviceType: "ClusterIP"
...
```

**Comment by ericsyh** [comment]
@futeng Which chart version you are using? I check it on 1.3.1 it should take effect.

Vault configs on `values.yaml`

```
vault:
  component: "vault"
  serviceAccount:
    created: true
    name: ""
  serviceType: "ClusterIP"
  tolerations: []
  nodeSelector:
    zone: default
  annotations: {}
  volumeClaimTemplates: []
  unsealConfig: {}
```

Vault statefulset configs by `kc edit sts snp-sn-platform-vault -n snp`

```
spec:
  template:
    spec:
      nodeSelector:
        zone: default
```

**Comment by futeng** [comment]
I should have posted the location of the file in the first place, [right here](https://github.com/streamnative/managed-clusters-cn/blob/master/clusters/zhilian/prod/pulsar/values.yaml).

@ericsyh Hi Eric, can you tell me how to find the version I used.

**Comment by ericsyh** [comment]
> I should have posted the location of the file in the first place, [right here](https://github.com/streamnative/managed-clusters-cn/blob/master/clusters/zhilian/prod/pulsar/values.yaml).
> 
> @ericsyh Hi Eric, can you tell me how to find the version I used.

@futeng You can run `helm list -a -A` to get the Chart version installed for example 

```
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                 	APP VERSION
snp            	snp      	1       	2022-04-25 13:58:28.086219 +0800 CST	deployed	sn-platform-1.3.1     	2.9
```

Your environment uses 1.3.1 Chart but i can not reproduce it on raw K8s and Azure AKS. The nodeSelector set takes effect on vaul Pod: 

```
kc get po snp-sn-platform-vault-0 -n snp -o yaml

spec:
  affinity: {}
  automountServiceAccountToken: true
  nodeSelector:
    zone: default
```

We'd better test on Huawei Cloud to check why not effect on thier K8s.
