### ISSUE TITLE
Convert clusterroles in sn-platform to namespace-scoped roles

### ISSUE THREAD

**Issue by fantapsody** [streamnative/charts#660]

**Comment by FushuWang** [comment]
## Components that have a switch to control role and cluster role
- Bookkeeper
- Broker
- Function Worker
- Prometheus
- Zookeeper
  - Backup
  - Restore

## Components that need cluster role
- Control Center
  - ingress-controller
- Custom Metric Server
  - prometheus
  - server
- External DNS

## Components that don't need role
- Toolset
- Streamnative-console
- Pulsarcoordinator
- Proxy 

## Others
- Vault 
   it has a role and  doesn't need a cluster role.

**Comment by FushuWang** [comment]
I have done an installation test. It seems like these components don't need to have a cluster role or role. Without the roles, their service pods are still working. @fantapsody 
- Bookkeeper
- Broker
- Function Worker
- Prometheus
- Zookeeper
  - Backup
  - Restore

**Comment by FushuWang** [comment]
For the purpose of converting clusterroles to namespace-scoped roles. We can just disable the clusterroles of bookkeeper, broker, function worker, prometheus, and zookeeper. Also disable the components control center, custom metric server, and external DNS, they are disabled by default.

```yaml
zookeeper:
  customTools:
    serviceAccount:
      clusterRole: false
bookkeeper:
  serviceAccount:
    clusterRole: false
broker:
  serviceAccount:
    clusterRole: false
function:
  serviceAccount:
    clusterRole: false
prometheus:
  serviceAccount:
    clusterRole: false
```
