### ISSUE TITLE
[sn-platform][feat] Support globally control monitoring components

### ISSUE THREAD

**Issue by maxsxu** [streamnative/charts#707]
## Motivation
Currently we control monitoring components by enabling or disabling a single component as following：

```
monitoring:
  prometheus: true
  grafana: true
  node_exporter: true
  alert_manager: true
  loki: false
  datadog: false
```

We want to improve user-friendliness by adding a new flag as shown below:

```
monitoring:
  enabled: true
```
