### ISSUE TITLE
[bug][sn-platform]: metrics scraping failed when istio enabled

### ISSUE THREAD

**Issue by ericsyh** [streamnative/charts#731]
### Background

When using istio 1.13.x, Prometheus metrics scraping will be failed when istio is enabled.  One workaround is to modify the Prometheus configmap and comment below configs: 

```
apiVersion: v1
data:
  prometheus.yml: |
    global:
      # scheme: https
      # tls_config:
      #  ca_file: /etc/prom-certs/root-cert.pem
      #  cert_file: /etc/prom-certs/cert-chain.pem
      #  key_file: /etc/prom-certs/key.pem
      #  insecure_skip_verify: true
```
I also tried to add `meshConfig.enablePrometheusMerge: false` on IstioOperator CR, but only broker pod is good to scrape merics, other pods like bookie/zk/autorecovery are all failed.
