### ISSUE TITLE
[pulsar] Some issues when enable tls

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/charts#815]
while deploy pulsar with below values: `helm install sn-platform --set initialize=true --values ./pulsar/mini_values.yaml ./pulsar --debug`

```yaml
tls:
  enabled: true
  proxy:
    enabled: true
  broker:
    enabled: true
  zookeeper:
    enabled: true
  bookkeeper:
    enabled: true

# issue selfsigning certs
certs:
  internal_issuer:
    enabled: true
    type: selfsigning
```

there are several issues:

1. the configmap of `sn-platform-pulsar-functions-worker-configfile` is broken like below:

```yaml
    functionRuntimeFactoryConfigs:
      jobNamespace: default
      pulsarDockerImageName: "streamnative/pulsar-all:2.9.2.23"
      pulsarRootDir: /pulsarpulsarAdminUrl: https://localhost:8443pulsarServiceUrl: pulsar+ssl://localhost:6651
      changeConfigMap: "sn-platform-pulsar-functions-worker-config"
      changeConfigMapNamespace: default
      submittingInsidePod: true
      installUserCodeDependencies: true
```

2. generated cert doesn't include `sn-platform-pulsar-broker-0.sn-platform-pulsar-broker.default.svc.cluster.local` as a DNS name but container `*.sn-platform-pulsar-broker-0.sn-platform-pulsar-broker.default.svc.cluster.local`

3. `.Values.tls.bookkeeper` is using while we should use `.Values.tls.bookie`
