### ISSUE TITLE
Change default security context to support running pulsar 2.10+

### ISSUE THREAD

**Issue by fantapsody** [streamnative/charts#826]
Like this:

```
zookeeper:
  securityContext:
    runAsNonRoot: true

bookkeeper:
  securityContext:
    runAsNonRoot: true

proxy:
  securityContext:
    runAsNonRoot: true

broker:
  securityContext:
    runAsNonRoot: true
```
