### ISSUE TITLE
[sn-platform] Unable to start broker and proxy when auth and vault disabled

### ISSUE THREAD

**Issue by maxsxu** [streamnative/charts#910]
## Description
The Broker and Proxy Pods are stuck on pending due to the below error:

```
MountVolume.SetUp failed for volume "secret-snp-token-asymmetric-key" : secret "snp-token-asymmetric-key" not found
```

and the pulsar detector will also stuck on pending due to the secret `snp-token-admin` not found.

## How to reproduce?
Deploy the sn-platform with the below values:

```
components:
  vault: false

auth:
  authentication:
    enabled: false
  authorization:
    enabled: false
```
