### ISSUE TITLE
[sn-platform] Support to add custom annotations and labels for CR

### ISSUE THREAD

**Issue by FushuWang** [streamnative/charts#930]
# Motivation
There are some feature flags triggered by specific annotations or labels.
So the sn-platform should support to add custom annotations and labels for CR, such as PulsarBroker, PulsarProxy. 

```yaml
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: "ok-sn-platform"
  namespace: default
  annotations:
    "cloud.streamnative.io/omit-init-sysctl": "true"
```
